language: python

os:
  - linux
  - osx

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - python3 -m pip install twine

script:
  - python3 setup.py build
  - python3 setup.py install
  - python3 test.py
  - python3 setup.py sdist bdist_wheel

after_success:
  - python3 -m twine upload --skip-existing dist/*

env:
  global:
    - TWINE_USERNAME=__token__
